### ISSUE TITLE
Apply font-size directly to the heading element.

### ISSUE THREAD

**Issue by josephtkim** [shannonj498/prj-rev-bwfs-dasmoto#1]
For the heading, it might appear much larger than expected. To fix the size, apply the font-size property directly to the h1 element, rather than to the div element, like so

```css
.heading h1 {
  font-size: 100px;
}
```
