### ISSUE TITLE
Simplify CSS for shared properties.

### ISSUE THREAD

**Issue by josephtkim** [shannonj498/prj-rev-bwfs-dasmoto#8]
It is a good idea to try and simplify the CSS code as much as you can to make the code cleaner and to remove repetitive code.  There are a few shared properties in the CSS, which you can simplify by applying to multiple selectors at once. For instance,

```css
h1, h2, .price {
  font-weight: bold;
}

h2 {
  font-size: 32px;
  color: white;
}
```
